CREATE TABLE IF NOT EXISTS `typecho_qiwi_comment_mail_queue` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dedupe_key` varchar(128) NOT NULL,
  `coid` int(10) unsigned NOT NULL DEFAULT '0',
  `cid` int(10) unsigned NOT NULL DEFAULT '0',
  `parent` int(10) unsigned NOT NULL DEFAULT '0',
  `recipient_type` varchar(16) NOT NULL DEFAULT '',
  `event` varchar(32) NOT NULL DEFAULT '',
  `recipient_mail` varchar(255) NOT NULL DEFAULT '',
  `recipient_name` varchar(255) NOT NULL DEFAULT '',
  `payload` longtext NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `attempts` int(10) unsigned NOT NULL DEFAULT '0',
  `last_error` text NULL,
  `next_retry` int(10) unsigned NOT NULL DEFAULT '0',
  `locked_until` int(10) unsigned NOT NULL DEFAULT '0',
  `sent_at` int(10) unsigned NOT NULL DEFAULT '0',
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `updated` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `dedupe_key` (`dedupe_key`),
  KEY `status_next_retry` (`status`, `next_retry`, `locked_until`, `id`),
  KEY `coid` (`coid`),
  KEY `recipient_type` (`recipient_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
